-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL oo_schema_output.txt

--student id: 34274723
--student name: Jichao Liang

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-02 00:43:27 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE BOOKING CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     addr_no      NUMBER (7)  NOT NULL , 
     street       VARCHAR2 (50)  NOT NULL , 
     town         VARCHAR2 (50)  NOT NULL , 
     postcode     CHAR (10)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.addr_no IS 'Address number' 
;

COMMENT ON COLUMN ADDRESS.street IS 'Address street' 
;

COMMENT ON COLUMN ADDRESS.town IS 'Address town' 
;

COMMENT ON COLUMN ADDRESS.postcode IS 'Address postcode' 
;

COMMENT ON COLUMN ADDRESS.country_name IS 'Address country name' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( addr_no ) ;

CREATE TABLE BOOKING 
    ( 
     bk_no     NUMBER (7)  NOT NULL , 
     pas_id    NUMBER (7)  NOT NULL , 
     cruise_id NUMBER (7)  NOT NULL , 
     cab_no    NUMBER (7)  NOT NULL , 
     ship_code NUMBER (7)  NOT NULL , 
     mani_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BOOKING.bk_no IS 'Booking number' 
;

COMMENT ON COLUMN BOOKING.pas_id IS 'Passenger ID' 
;

COMMENT ON COLUMN BOOKING.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN BOOKING.cab_no IS 'Cabin number' 
;

COMMENT ON COLUMN BOOKING.ship_code IS 'Ship code' 
;

COMMENT ON COLUMN BOOKING.mani_name IS 'Manifest name' 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( bk_no ) ;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_NK UNIQUE ( pas_id , cruise_id , cab_no , ship_code ) ;

CREATE TABLE CABIN 
    ( 
     cab_no       NUMBER (7)  NOT NULL , 
     ship_code    NUMBER (7)  NOT NULL , 
     slp_capacity CHAR (10)  NOT NULL , 
     cab_class    CHAR (10)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabclass 
    CHECK (cab_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cab_no IS 'Cabin number' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'Ship code' 
;

COMMENT ON COLUMN CABIN.slp_capacity IS 'Cabin sleeping capacity' 
;

COMMENT ON COLUMN CABIN.cab_class IS 'Cabin class, I-Interior, O-Ocean view, B-Balcony, S-Suite' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cab_no, ship_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id           NUMBER (7)  NOT NULL , 
     departure_date_time DATE  NOT NULL , 
     cruise_name         VARCHAR2 (50)  NOT NULL , 
     description         VARCHAR2 (100)  NOT NULL , 
     ship_code           NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN CRUISE.departure_date_time IS 'Departure date and time' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Cruise name' 
;

COMMENT ON COLUMN CRUISE.description IS 'Cruise description' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'Ship code' 
;
CREATE UNIQUE INDEX CRUISE__IDX ON CRUISE 
    ( 
     ship_code ASC 
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     mani_name         VARCHAR2 (50)  NOT NULL , 
     pas_bod_date_time DATE 
    ) 
;

COMMENT ON COLUMN MANIFEST.mani_name IS 'Manifest name' 
;

COMMENT ON COLUMN MANIFEST.pas_bod_date_time IS 'Passenger boarding date and time if board ' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( mani_name ) ;

CREATE TABLE OPERATOR 
    ( 
     op_id    NUMBER (7)  NOT NULL , 
     cp_name  VARCHAR2 (50)  NOT NULL , 
     ceo_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.op_id IS 'Operator ID' 
;

COMMENT ON COLUMN OPERATOR.cp_name IS 'Operate company name' 
;

COMMENT ON COLUMN OPERATOR.ceo_name IS 'Operate company CEO name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( op_id ) ;

CREATE TABLE PASSENGER 
    ( 
     pas_id      NUMBER (7)  NOT NULL , 
     pas_fstname VARCHAR2 (50)  NOT NULL , 
     pas_lstname VARCHAR2 (50)  NOT NULL , 
     pas_gender  CHAR (10)  NOT NULL , 
     gas_dob     DATE  NOT NULL , 
     gud_phone   CHAR (10) , 
     gud_id      NUMBER (7) , 
     addr_no     NUMBER (7)  NOT NULL , 
     pas_id1     NUMBER (7) 
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT chk_pasgender 
    CHECK (pas_gender IN ('F', 'M', 'O')) 
;

COMMENT ON COLUMN PASSENGER.pas_id IS 'Passenger ID' 
;

COMMENT ON COLUMN PASSENGER.pas_fstname IS 'Passenger first name' 
;

COMMENT ON COLUMN PASSENGER.pas_lstname IS 'Passenger last name' 
;

COMMENT ON COLUMN PASSENGER.pas_gender IS 'Passenger gender, F-Female, M-Male, O-Others' 
;

COMMENT ON COLUMN PASSENGER.gas_dob IS 'Passenger date of birth' 
;

COMMENT ON COLUMN PASSENGER.gud_phone IS 'Passenger contact phone number.If minors, use guardian phone number' 
;

COMMENT ON COLUMN PASSENGER.gud_id IS 'Guardian ID if minors' 
;

COMMENT ON COLUMN PASSENGER.addr_no IS 'Address number' 
;

COMMENT ON COLUMN PASSENGER.pas_id1 IS 'Passenger ID' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( pas_id ) ;

CREATE TABLE SHIP 
    ( 
     ship_code   NUMBER (7)  NOT NULL , 
     ship_name   VARCHAR2 (50)  NOT NULL , 
     com_date    DATE  NOT NULL , 
     ship_ton    CHAR (10)  NOT NULL , 
     max_gst_cap CHAR (10)  NOT NULL , 
     reg_country VARCHAR2 (50)  NOT NULL , 
     op_id       NUMBER (7)  NOT NULL , 
     cruise_id   NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'Ship code' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Ship name' 
;

COMMENT ON COLUMN SHIP.com_date IS 'Ship commission date' 
;

COMMENT ON COLUMN SHIP.ship_ton IS 'Ship tonnage' 
;

COMMENT ON COLUMN SHIP.max_gst_cap IS 'Ship maximum guest capacity' 
;

COMMENT ON COLUMN SHIP.reg_country IS 'Ship register country' 
;

COMMENT ON COLUMN SHIP.op_id IS 'Operator ID' 
;

COMMENT ON COLUMN SHIP.cruise_id IS 'Cruise ID' 
;
CREATE UNIQUE INDEX SHIP__IDX ON SHIP 
    ( 
     cruise_id ASC 
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT addr_pas_fk FOREIGN KEY 
    ( 
     addr_no
    ) 
    REFERENCES ADDRESS 
    ( 
     addr_no
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT cab_bk_fk FOREIGN KEY 
    ( 
     cab_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cab_no,
     ship_code
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT cruise_bk_pk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT cruise_ship_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT cruise_ship_fkv2 FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT mani_bk_fk FOREIGN KEY 
    ( 
     mani_name
    ) 
    REFERENCES MANIFEST 
    ( 
     mani_name
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT op_ship_fk FOREIGN KEY 
    ( 
     op_id
    ) 
    REFERENCES OPERATOR 
    ( 
     op_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT pas_bk_pk FOREIGN KEY 
    ( 
     pas_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pas_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT pas_pas_fk FOREIGN KEY 
    ( 
     pas_id1
    ) 
    REFERENCES PASSENGER 
    ( 
     pas_id
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cab_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             2
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off